version = 1


[*]
n-gpu-layers = -1
ctx-size = 8192
jinja = true
stop-timeout = 30

[gpt-oss-20b]
model = /opt/models/gpt-oss-20b/gpt-oss-20b-Q4_K_M.gguf
ctx-size = 16384
load-on-startup = true

[nemotron-3-super-120b]
model = /opt/models/nemotron-3-super-120b/UD-Q4_K_XL/NVIDIA-Nemotron-3-Super-120B-A12B-UD-Q4_K_XL-00001-of-00003.gguf
ctx-size = 16384
temp = 0.6
top-p = 0.95

[qwen3-next-80b]
model = /opt/models/qwen3-next-80b/Qwen3-Next-80B-A3B-Instruct-UD-Q4_K_XL.gguf
n-gpu-layers = 99
ctx-size = 65536
flash-attn = true

[qwen3-coder-30b]
model = /opt/models/qwen3-coder-30b/Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf
ctx-size = 32768

[qwen2.5-vl-32b]
model = /opt/models/qwen2.5-vl-32b/qwen2.5-vl-32b-instruct-q4_k_m.gguf
ctx-size = 8192

[Qwen3.5-0.8B-Q8_0-uncensored]
model = /models/Qwen3.5-0.8B-heretic.Q8_0.gguf
mmproj = /models/mmproj-Qwen3.5-F16.gguf
; Context size
c = 20000
; Temperature
temp = 0.7
; Top P
top-p = 0.80
; Min P
min-p = 0.0
; Top K
top-p = 0.20
; Presence Penalty
presence-penalty = 1.5
; Repetition Penalty
repeat-penalty = 1.0
; Flash Attention
; flash-attn = true
; Performance tweaks
; n-gpu-layers = 100
; Json test
; json-schema-file = /config/invoice.json


