"C:\Program Files\Mozilla Firefox\firefox.exe" ^
	http://www.google.com/search?q="virtual pc" ^
	http://www.google.com/search?q="Vmware player" ^
	http://www.google.com/search?q="mono project" ^
	http://www.google.com/search?q="mono project" ^
	http://www.google.com/search?q="sharpdevelop" ^
	http://www.google.com/search?q="notepad++" ^
	http://www.google.com/search?q="winscp" ^
	http://www.google.com/search?q="soapui" ^
	http://www.google.com/search?q="hp usb format disk" ^
	http://www.google.com/search?q="mysql" ^
	http://www.google.com/search?q="sqlserver" ^
	http://www.google.com/search?q="net penguin" ^
	http://www.google.com/search?q="foxit" ^
	http://www.google.com/search?q="gizmo" ^
	http://www.google.com/search?q="visual studio powercommands" ^
	http://www.google.com/search?q="wireshark" ^
	http://www.google.com/search?q="nmap" ^
	http://www.google.com/search?q="sysinternals" ^
	http://www.google.com/search?q="putty" ^
	http://www.google.com/search?q="vlc" ^
	http://www.google.com/search?q="vista codecs" ^
