# Install Applications
choco install fiddler4
choco install notepadplusplus
choco install visualstudiocode
choco install greenshot 
choco install GoogleChrome
choco install putty
choco install ccleaner
choco install skype
choco install beyondcompare 
choco install resharper-platform
choco install linqpad
choco install spotify

# Install Utilities
choco install dropbox
choco install googledrive 
choco install sysinternals
choco install procmon 
choco install windirstat 
choco install msysgit
choco install gitextensions
choco install tortoisegit
choco install 7zip
choco install vcredist2010 
choco install rdcman 
choco install TeraCopy 
choco install logparser 
choco install tor-browser 
choco install PowerShellGAC
choco install procexp
choco install cmder
